"""product table

Revision ID: c3764e8bc2d0
Revises: 1898979be78f
Create Date: 2019-03-31 10:32:39.545389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3764e8bc2d0'
down_revision = '1898979be78f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('desc', sa.String(length=600), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('img', sa.String(length=300), nullable=True),
    sa.Column('sub_cat_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sub_cat_id'], ['sub_category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product')
    # ### end Alembic commands ###
